# Generated by Django 3.0 on 2019-12-07 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialfeedapp', '0002_appgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialfeedapp.AppGroup'),
        ),
    ]
